import math

RES = WIDTH, HEIGHT = 640, 480
HALF_WIDTH = WIDTH//2
HALF_HEIGHT = HEIGHT//2
FPS = 60
SIZE = 64

PLAYER_POS = 1.5, 5
PLAYER_ANGLE = 0
PLAYER_SPEED = 0.004
PLAYER_ROT_SPEED = 0.003

FOV = math.pi / 3
HALF_FOV = FOV/2
NUM_RAYS = WIDTH // 2
HALF_NUM_RAYS = NUM_RAYS // 2

DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 15

SCREEN_DIST = HALF_WIDTH / math.tan(HALF_FOV)
SCALE = WIDTH // NUM_RAYS